spring.devtools.restart.enabled=true
spring.mongodb.uri=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb-dev:27017/smartfridge?authSource=admin

jwt.secret=${JWT_SECRET}
jwt.expiration=14400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.root=INFO
logging.level.ch.css.backend=DEBUG
