spring.mongodb.uri=${MONGO_PROD_URI}

jwt.secret=${JWT_SECRET}
jwt.expiration=14400000

logging.level.root=WARN
logging.level.ch.css.backend=INFO

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false