FROM node:alpine AS build

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

FROM node:alpine

RUN npm install -g serve

COPY --from=build /app/dist/smart-fridge-frontend/browser /app

EXPOSE 80

CMD ["serve", "-s", "/app", "-l", "80"]
